remote_theme: aterenin/minima-reboot

header_pages:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "New Link"
    url: "https://newlink.com"
    
footer_icons:
- username: 2111219
  url: https://github.com/aterenin/minima-reboot/
